### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by xiang-xiang-zhu** [lxchtan/TEGTOK#1]
Is the current code the full version? I see you said it will be updated. Can you provide a guide on how to reproduce the results using code? Thanks

**Comment by lxchtan** [comment]
Thank you for your interest in our work.
The current code can reproduce the results following [Instruction](https://github.com/lxchtan/TEGTOK#instruction).
I have now updated the evaluation code to that repo, and updated the [Evaluation](https://github.com/lxchtan/TEGTOK#evaluation) accordingly.
If you have any other questions, feel free to ask.
