### ISSUE TITLE
About reproduce the result of task question generation?

### ISSUE THREAD

**Issue by xiang-xiang-zhu** [lxchtan/TEGTOK#2]
Hello, when I used the code you provided to reproduce the task of question generation, the results I got were much lower than those in the paper. For example, the BLEU-1 of the SQuAD dataset in the paper is 46.57, but the result I got was only 27.42. However, comparable results to the paper can be obtained on the dialogue generation task.
What is the wrong step? Thanks

The scripts I use in question generation is 
`python -u trainer.py --params_file config/squad_nqg/TegTok.json --output_path TegTok_nqg --n_epochs 15 --train_batch_size 8 --valid_batch_size 8 --gradient_accumulation_steps 8 `

**Comment by lxchtan** [comment]
Hello, did you evaluate the SQuAD using the tools offer by [xinyadu/nqg: neural question generation for reading comprehension](https://github.com/xinyadu/nqg) as mentioned in [Evaluation](https://github.com/lxchtan/TEGTOK#evaluation)? Or did you get the same numbers in paper by evaluating the file `results/Paper/TegTok_squad_nqg.txt`?

**Comment by xiang-xiang-zhu** [comment]
Thank you for your reply. I tried to use the tools provided by https://github.com/xinyadu/nqg to test. I generated the src file and tgt file myself and tested it with the txt file provided in results/Paper. This is the result I got
scores: 

Bleu_1: 0.20642
Bleu_2: 0.05054
Bleu_3: 0.01803
Bleu_4: 0.00682

It still seems to be relatively low.

**Comment by xiang-xiang-zhu** [comment]
> Hello, did you evaluate the SQuAD using the tools offer by [xinyadu/nqg: neural question generation for reading comprehension](https://github.com/xinyadu/nqg) as mentioned in [Evaluation](https://github.com/lxchtan/TEGTOK#evaluation)? Or did you get the same numbers in paper by evaluating the file `results/Paper/TegTok_squad_nqg.txt`?

Thank you for your reply. I tried to use the tools provided by https://github.com/xinyadu/nqg to test. I generated the src file and tgt file myself and tested it with the txt file provided in results/Paper. This is the result I got
scores: 

Bleu_1: 0.20642
Bleu_2: 0.05054
Bleu_3: 0.01803
Bleu_4: 0.00682

It still seems to be relatively low.

**Comment by lxchtan** [comment]
How did you run the scripts?

```shell
cd qgevalcap
./eval.py -out ../results/Paper/TegTok_squad_nqg.txt
```

And I get the results

```shell
scores:

Bleu_1: 0.46576
Bleu_2: 0.30638
Bleu_3: 0.22259
Bleu_4: 0.16729
METEOR: 0.20360
ROUGE_L: 0.43620
```

**Comment by xiang-xiang-zhu** [comment]
> How did you run the scripts?
> 
> ```shell
> cd qgevalcap
> ./eval.py -out ../results/Paper/TegTok_squad_nqg.txt
> ```
> 
> And I get the results
> 
> ```shell
> scores:
> 
> Bleu_1: 0.46576
> Bleu_2: 0.30638
> Bleu_3: 0.22259
> Bleu_4: 0.16729
> METEOR: 0.20360
> ROUGE_L: 0.43620
> ```
Thanks. I think I get it. Because the test_id in the test.json file is scrambled. I rearranged the order of the generated files. When I run the script, the provided TegTok_squad_nqg.txt can achieve the results in the paper. But the results generated by the model I trained myself are still relatively low.
```
scores: 

Bleu_1: 0.32868
Bleu_2: 0.22449
Bleu_3: 0.16360
Bleu_4: 0.12263
```

I then viewed the contents of both files.
The first ten sentences in TegTok_squad_nqg.txt are:

```
1. when did the virgin mary appear to saint bernadette soubirous ?
2. what legend surrounds the statue of christ in front of the main building ?
3. what is the basilica of the sacred heart next to ?
4. where is the grotto located ?
5. what is at the top of the church of the virgin mary ?
6. when was scholastic published ?
7. what is the name of the other magazine at washington university ?
8. what type of news is the observer primarily reporting ?
9. how many student-run outlets does the university have ?
10. when was common sense published ?
```

The first ten sentences in the generated file of my own training are:

```
1. in what year did mary appear at the basilica of lourdes?
2. what is depicted on the bronze statue of christ in front of the main building?
3. what is the basilica of the sacred heart next to?
4. what is the grotto?
5. what is on the main building's gold dome?
6. when was scholastic published?
7. how many times is the juggler published?
8. how many students are in the observer?
9. how many student-run outlets does washington university have?
10. when was common sense published?
```

It seems that the difference in the generated content is still relatively large.

**Comment by lxchtan** [comment]
Sorry for the test_id problems. I update a file `analyse/convert_squad_nqg_output_format.py` to match the output format.
You can try to use it before evaluation. 

I just reran the code `bash run_shell/S1_TegTok_nqg.sh 43`
and then converted the output format with `analyse/convert_squad_nqg_output_format.py` to evaluate with `./eval.py -out ../results/20230227_TegTok_nqg_43_single_example_format.txt`. The results are similar to those shown in the paper.

**Comment by xiang-xiang-zhu** [comment]
> Sorry for the test_id problems. I update a file `analyse/convert_squad_nqg_output_format.py` to match the output format. You can try to use it before evaluation.
> 
> I just reran the code `bash run_shell/S1_TegTok_nqg.sh 43` and then converted the output format with `analyse/convert_squad_nqg_output_format.py` to evaluate with `./eval.py -out ../results/20230227_TegTok_nqg_43_single_example_format.txt`. The results are similar to those shown in the paper.

Thanks a lot!  I'd like to ask again, have you encountered this problem when using nqg's eval script

```
Traceback (most recent call last):
  File "./eval.py", line 104, in <module>
    eval(args.out_file, args.src_file, args.tgt_file)
  File "./eval.py", line 94, in eval
    return QGEval.evaluate()
  File "/home/hx/TEGTOK/qgevalcap/eval.py", line 37, in evaluate
    score, scores = scorer.compute_score(self.gts, self.res)
  File "/home/hx/TEGTOK/qgevalcap/meteor/meteor.py", line 42, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/home/hx/TEGTOK/qgevalcap/meteor/meteor.py", line 61, in _stat
    self.meteor_p.stdin.write('{}\n'.format(score_line.encode('utf-8')))
IOError: [Errno 32] Broken pipe
```
I create a python2.7 env for this eval scripts.

**Comment by lxchtan** [comment]
Did you install the jdk?
I create the eval env with `conda create -n coco python=2.7 openjdk=8 numpy`.
